name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: antoninklopp/cs-to-ts-action@v1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/cs-to-ts.yml
